--- # ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: sync

on:
  schedule:
    - cron: "22 22 * * *"
  workflow_dispatch:

jobs:
  sync:
    strategy:
      matrix:
        branch: ["release-1.8.x", "release-1.9.x", "release-1.10.x"]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Install Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.x"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # We need to provide either a Personal Access Token or a SSH Key as suggested in
          # https://medium.com/prompt/trigger-another-github-workflow-without-using-a-personal-access-token-f594c21373ef
          ssh-key: "${{ secrets.PUSH_KEY }}"
          ref: ${{ matrix.branch }}
          fetch-depth: 0
          persist-credentials: true
      - name: Git set bot identity
        env:
          CI_USER: "github-actions[bot]"
          CI_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"             
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
      - name: Sync with upstream
        uses: squakez/sync-cherry-pick@v0
        with:
          upstream-org: "apache"
          upstream-repo: "camel-k"
          upstream-branch: ${{ matrix.branch }}
          downstream-branch: ${{ matrix.branch }}
      - name: Vendor refresh
        uses: squakez/sync-go-vendor@v0
        with:
          go-src-path: "./pkg/..."
      - name: Pin init directory divergencies
        uses: squakez/sync-pin-divergencies@v0
        with:
          init-directory: "ci/downstream"          
      - name: Git push          
        run: |
          git push origin HEAD:${{ matrix.branch }}


